---
title: "Introduzione"
# author: "Mattia Doro"
# date: "3/10/2022"
output: 
  html_document:
    self_contained: true
---

```{r setup, include=FALSE}
setwd("C:/Users/admin/Dropbox/Courses/ARCA/2022/")
knitr::opts_chunk$set(echo = TRUE)


```

Le toolbox **EEGLAB** e **ERPLAB**, utilizzabili in ambiente **MATLAB**, permettono di analizzare dati elettroencefalografici (EEG). Il corso si propone di fornire le competenze necessarie per l’analisi dati di base, offrendo inoltre la possibilità di comprendere aspetti teorici attraverso esempi pratici. I contenuti trattati saranno principalmente il pre-processamento dei dati (filtri del segnale, ri-referenziamento, rimozione/interpolazione di segnale rumoroso, segmentazione, rimozione artefatti, correzione artefatti con analisi delle componenti indipendenti) e al computo di potenziali evento-relati (ERPs). 


### Programma

*Lunedì 21/11*

- L'ambiente MATLAB
- Le toolbox EEGLAB/ERPLAB
- Caricare i dati in EEGLAB/ERPLAB

*Martedì 22/11*


*Mercoledì 23/11*


*Giovedì 24/11*


*Venerdì 25/11*

# Requisiti
Si raccomanda di installare nel proprio computer il software MATLAB prima dell’inizio del corso (nel caso l’abbiate fatto in precedenza, consiglio di disinstallarlo e reinstallare l’ultima versione -2022b-, così da non rischiare alcuna incompatibilità). C’è la possibilità di scaricarlo gratuitamente con l’account istituzionale (@studenti.unipd.it). A [questo link](https://asit.unipd.it/servizi/servizi-utenti-istituzionali/contratti-software-licenze/matlab) sono presenti tutte le istruzioni (sezione "Download del software").

Le toolbox EEGLAB e ERPLAB sono scaricabili gratuitamente, così come il software MATLAB (quest’ultimo utilizzando l’indirizzo e-mail dell’Università di Padova).
Per ottimizzare le tempistiche del corso, invito ad installare il software MATLAB prima dell'inizio del corso (eventualmente con un po' di anticipo, così da potermi contattare se si riscontrassero difficoltà).
Per un utilizzo corretto delle toolbox EEGLAB e ERPLAB, in fase di installazione di MATLAB, è necessario installare anche i seguenti pacchetti aggiuntivi (sarà sufficiente selezionarli da una lista):

- Image Processing Toolbox
- Optimization Toolbox
- Signal Processing Toolbox
- Statistics and Machine Learning Toolbox



EEGLAB (e ERPLAB in questo caso già contenuto all'interno del primo) può essere scaricato [qui](https://drive.google.com/drive/folders/1_N4_UB2yvqnrQwvGe-9KiUPbGu6UdLAr?usp=sharing) come un unico pacchetto compresso (da decomprimere). Le toolbox non necessitano di alcuna installazione, vedremo in aula come spiegare a MATLAB che vogliamo usarle.

# Materiali






